### ISSUE TITLE
Bug on facebook

### ISSUE THREAD

**Issue by tin-pham** [glacambre/firenvim#1330] opened 2022-03-06 12:13 UTC
- OS Version: PopOS 21.10
- Browser Version: Vivaldi 5.0.2497.32
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 0.7.0dev

### What I tried to do
- Use this plugin on facebook

### What happened
- I can write but whenever i type something it appear this (Sorry i can't capture the full bug because the text box of facebook is very small)
![image](https://user-images.githubusercontent.com/20679090/156922463-b6654be3-2dd4-44f3-aaf0-9763bc78a476.png)
- Right now it just being like this on facebook. Reddit, github work fine

**Comment by glacambre** [comment] 2022-03-06 12:22
You can get the full message by either:
- Changing the size of the textbox with `:set lines=30 columns=120`
- Running `:redir > /tmp/errors`, triggering the error and then using `:redir END`. This will create a file named `/tmp/errors` which will contain everything that was printed.

Your screenshot contains a lot of plugin paths that aren't related to firenvim. Could you disable every plugin except firenvim and try again?

**Comment by tin-pham** [comment] 2022-03-06 12:39
![image](https://user-images.githubusercontent.com/20679090/156923476-1a165e83-b06c-49b5-ac94-9fa18cff41fe.png)
![image](https://user-images.githubusercontent.com/20679090/156923496-4319c182-3343-465a-9694-4de10aa1778a.png)
![image](https://user-images.githubusercontent.com/20679090/156923578-677fcc5a-9d8b-4112-8635-4d3f99bbace2.png)

When ever i increase size for text box, the bug disappear and everything work normal, also it took me a while to take the third pic because the bug just disappear right away

**Comment by glacambre** [comment] 2022-03-06 13:16
The error message states `nvim-cmp/lua/cmp/utils/window.lua:144: 'height' key must be a positive Integer`, so this is a nvim-cmp bug, not a Firenvim bug. I'll close this issue but feel free to ask any other question you may have :)

**Closed by glacambre** 2022-03-06 13:16 UTC

**Comment by tin-pham** [comment] 2022-03-07 00:44
How can I link another config to firenvim, when i do like this it bug
![image](https://user-images.githubusercontent.com/20679090/156949993-c4f349a5-b754-423d-859a-ed6cca565009.png)
![image](https://user-images.githubusercontent.com/20679090/156950002-8ec96460-7fa3-4d27-940b-e983807d589c.png)
 
![image](https://user-images.githubusercontent.com/20679090/156950036-96fa659e-4453-4c04-8428-0b60520d284e.png)

**Comment by glacambre** [comment] 2022-03-07 04:48
The backtrace says that the problem is in `options/init.lua`. Remove the content of this file line by line until you figure out what is causing the problem.

**Comment by tin-pham** [comment] 2022-03-07 04:50
When I add this to options/init.lua
![image](https://user-images.githubusercontent.com/20679090/156969874-35106efc-a032-41ea-833d-3766f97fa92f.png)

It cause the problem

**Comment by glacambre** [comment] 2022-03-07 05:43
You can't do `source /home/shin/.config/nvim/init.lua` - this causes a require loop. Remove that line from your config and things should start working, assuming you don't have another loop in firenviminit.lua.
