### ISSUE TITLE
firenvim doesn't appear to work in chrome

### ISSUE THREAD

**Issue by jsholmes** [glacambre/firenvim#129] opened 2019-10-01 17:55 UTC
- OS Version: 10.14.5 (mojave)
- Browser Version:  77.0.3865.90
- What I tried to do: use firenvim on txti.es
- What happened: nothing.  normal browser text box.
- What I expected: firenvim.

I followed the troubleshooting instructions to the end and there is nothing in the browser console showing up when I click in the text area on txti.es or on the firenvim button in the toolbar in chrome.

This works:
```
❯ echo 'abcde{}' | /Users/john/.local/share/firenvim/firenvim
d{"version": "0.1.9", "settings": {"localSettings": {".*": {"priority": 0, "selector": "textarea"}}}}

```
This seems fine:
```
❯ cat $HOME/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/firenvim.json
{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "/Users/john/.local/share/firenvim/firenvim", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```

**Comment by justinmk** [comment] 2019-10-01 19:03
Do you see anything in devtools console? 
See also #125

**Comment by glacambre** [comment] 2019-10-01 19:19
Are you sure there aren't any errors in the background console? (the one you access by going to `chrome://extensions`, enabling Developer mode and clicking on the `background page` link of the extension)

**Comment by jsholmes** [comment] 2019-10-02 02:05
I see nothing in either the background console or the devtools console.

One note:
```echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim```
does not work.  (I don't have XDG_DATA_HOME defined it seems)

However, 
```echo 'abcde{}' | /Users/john/.local/share/firenvim/firenvim```
works fine.

**Comment by jsholmes** [comment] 2019-10-02 02:18
Oh wait!  I do see an error in dev console.  

```Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at content.ts:220
(anonymous) @ content.ts:220
```

in this function
```browser.storage.local.get("localSettings").then(async ({ localSettings }: { [key: string]: { [key: string]: any }}) => {
    function or1(val: number) {
        if (val === undefined) {
            return 1;
        }
        return val;
    }
    const [, conf] = Array.from(Object.entries(localSettings))
        .sort((e1, e2) => (or1(e2[1].priority) - or1(e1[1].priority)))
        .find(([pat, sel]) => (new RegExp(pat)).test(document.location.href));
    if (conf.selector) {
        setupListeners(conf.selector);
    }```

**Comment by jsholmes** [comment] 2019-10-02 02:18
So it's same as #125

**Comment by glacambre** [comment] 2019-10-02 08:31
It's not necessarily the same issue as #125 - in both cases, the browser has trouble running neovim (or more precisely, running the native messenger that runs neovim) but the causes are probably widely different, given the different operating systems these bugs happen on. Could you upload the content of `/Users/john/.local/share/firenvim/firenvim` here?

**Comment by jsholmes** [comment] 2019-10-03 14:45
```
 /Users/john ──────────────────────────────────── 10:44:40
❯ bat /Users/john/.local/share/firenvim/firenvim
──────────────
       │ File: /Users/john/.local/share/firenvim/firenvim
──────────────
   1   │ #!/bin/sh
   2   │ cd /Users/john/.local/share/firenvim
   3   │ exec '/usr/local/Cellar/neovim/HEAD-0b71bb7/bin/nvim' --headless -c 'call firenvim#run()'
─────────────
```

**Comment by glacambre** [comment] 2019-10-03 16:07
Thanks.

Try replacing the script with this:
```sh
#!/bin/sh
cd /Users/john/.local/share/firenvim
touch /tmp/firenvim_ran
exec '/usr/local/Cellar/neovim/HEAD-0b71bb7/bin/nvim' --headless -c 'call firenvim#run()' 2>/tmp/firenvim_errors
```

Then, try running firenvim twice (e.g. by reloading your config twice or clicking on a textarea twice) and see if it creates the firenvim_ran/firenvim_errors files. If it does, please upload the content of firenvim_errors here.

**Comment by jsholmes** [comment] 2019-10-04 00:09
``` cat /tmp/firenvim_errors
[coc.nvim] node is not executable, checkout https://nodejs.org/en/download/[coc.nvim] node is not executable, checkout https://nodejs.org/en/download/
Press ENTER or type command to continue%```

**Comment by jsholmes** [comment] 2019-10-04 00:17
```
 /Users/john ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 0.136s 20:17:18
❯ which -a node
/usr/local/bin/node

 /Users/john ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 0.081s 20:17:21
❯ node --version
v12.10.0
```

**Comment by jsholmes** [comment] 2019-10-04 01:42
Ok.  I've adjusted my script to be:
```
#!/bin/sh
cd /Users/john/.local/share/firenvim
exec env IN_FIRENVIM=1 '/usr/local/bin/nvim' --headless -c 'call firenvim#run()'
```

And this is working.  I can pick which plugins to use inside of firenvim, etc.

Indeed, I'm writing this comment inside an nvim.  Yay!

**Comment by glacambre** [comment] 2019-10-04 05:19
Ah, yeah, $PATH problems can be fixed by following [this section](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-firenvims-path-is-the-same-as-neovims) of the troubleshooting guide.

**Closed by glacambre** 2019-10-04 05:19 UTC

**Comment by jsholmes** [comment] 2019-10-04 15:20
I think labeling this a "$PATH Problem" leaves your program pretty brittle, but that's just me.  Thanks for the help.

**Comment by glacambre** [comment] 2019-10-04 16:17
OSX empties your $PATH when you run your browser and there's nothing I can do to prevent that. I can't set it to the right value every time the native messenger is ran because it might be scattered around (e.g. in your .bashrc, .zshrc, .zshenv, .fishrc…).

**Comment by glacambre** [comment] 2019-10-04 18:01
I tried to improve things a little bit in 977235e2c98db12431269ba051946a4a9f7e0b86 - firenvim should be usable on OSX without any intervention right after running `firenvim#install()`. However it will break as soon as your `$PATH` changes. Hopefully people don't do that often.

Could you try it out? Should just be a matter of updating the neovim plugin and running `:call firenvim#install()`.
