### ISSUE TITLE
Mac OS Mojave Install Failed

### ISSUE THREAD

**Issue by prmichaelsen** [glacambre/firenvim#16] opened 2019-05-23 17:14 UTC
I had some trouble installing firenvim on Mac OS Mojave. I was wondering if anyone would be able to help me troubleshoot. I can post install logs, if that would help.

**Comment by glacambre** [comment] 2019-05-23 18:06
Hi, thanks for reporting this issue :).

I don't have a Mac OS computer so I have not actually tested whether firenvim works there, sorry. I just took a look at the native messenger's source code and realized there was a typo in the manifest's path. I fixed it and pushed the change, could you pull my changes and try building firenvim again to see if this was the only issue?

**Comment by prmichaelsen** [comment] 2019-05-23 20:55
Sure thing! I will let you know once I’ve tried it

**Comment by pvinis** [comment] 2019-08-05 11:36
Any news on this? Is there a way to use firenvim on mac?

**Comment by glacambre** [comment] 2019-08-05 12:27
@pvinis Yes, there should be. Try [installing from source](https://github.com/glacambre/firenvim#from-source). I can't guarantee it works because I don't have a mac to test firenvim on. If you encounter any issues, please let me know.

**Comment by pvinis** [comment] 2019-08-06 07:49
So this is what I found out

one thing is that i had to rename the script `install` to `iinstall` in `package.json` because i use yarn :D 

I ran the steps to install it, I didnt have nvim >0.4 the first time so it was failing. I installed neovim head so its >0.4 now, and the install script is running fine.

Now my firefox has the black frame around the textarea, but no interaction is happening. I tried with firefox beta with the addon from mozilla's site, and I tried firefox dev edition with the xpi zip that i generated. I also saw there is a `target/firefox` dir that I didnt use.

The order I did was build and install, then install the add on on dev edition, just a black frame. then i ran the install script again, still black frame.

So I'm one step closer, but still not there. Does that give you an idea? Could you maybe point me to things that I could try or where the xpi is generated or some way to debug the connection or something?

**Comment by pvinis** [comment] 2019-08-06 07:51
Also, where is the script generation? The part that creates the `.exe` and the linux script, so maybe I can add the mac one.

**Comment by glacambre** [comment] 2019-08-06 09:14
>one thing is that i had to rename the script install to iinstall in package.json because i use yarn :D

Oh, I didn't know this would be a problem, thanks for telling me. I'll rename that step to something else.

>Now my firefox has the black frame around the textarea

Great! This means that you correctly built the extension but that there's a problem connecting to neovim.

>Could you maybe point me to things that I could try or where the xpi is generated or some way to debug the connection or something?

Executable binaries aren't needed anymore if you're using HEAD (they used to be in previous versions).

The browser console should log a few messages that would tell us what's wrong. You can open it like this: hamburger menu > `Web Developer` > `Browser Console`.

Could you also check if you have a native manifest file named `firenvim.json` in `~/Library/Application Support/Mozilla/NativeMessagingHosts/` and if you do, paste its content here? This file should contain a json object which has a key named `path`. Its value should be a path to a shell script. Could you make sure that this script exists and is executable and upload its content here?

**Comment by pvinis** [comment] 2019-08-06 09:25
Here is the console. Nothing interesting I guess.
![Screenshot 2019-08-06 at 11 24 10](https://user-images.githubusercontent.com/100233/62528193-bb36f380-b83c-11e9-8266-70a75b6d8531.png)

Here is the content of the NativeMessagingHosts file `{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "/Users/pvinis/.local/share/firenvim/firenvim", "type": "stdio", "allowed_extensions": ["firenvim@lacamb.re"]}`

I tried to run the file in `~/.local/share/firenvim/firenvim` and got
```
Error detected while processing command line:
E117: Unknown function: firenvim#run
Press ENTER or type command to continue
```

**Comment by pvinis** [comment] 2019-08-06 09:26
I asked for the executable binaries to I can maybe help create one for mac, so other mac users can install without the need to clone etc.

**Comment by glacambre** [comment] 2019-08-06 09:32
> E117: Unknown function: firenvim#run

Ah, that's interesting, this means that firenvim isn't correctly installed in neovim. How did you install it? Does sticking `set rtp+=$PATH_TO_THE_FIRENVIM_GIT_REPOSITORY` make this issue disappear?

>I asked for the executable binaries to I can maybe help create one for mac

They're really not needed anymore, I'll remove the ones I have [here](https://github.com/glacambre/firenvim/releases) when I release a new firenvim version on addons.mozilla.org. Everything is done in vimscript, lua and shell now :).

**Comment by pvinis** [comment] 2019-08-06 09:39
Ok, progress!

I run `nvim  -c ':set rtp+=/Users/pvinis/Source/temp/firenvim' -c 'call firenvim#run()' --headless` manually and it waits there. Also if i add the extra part in the firenvim script it runs with no errors, and it just waits there.

Then I refresh the page, and I get this
![Screenshot 2019-08-06 at 11 39 09](https://user-images.githubusercontent.com/100233/62529385-d571d100-b83e-11e9-99c3-dc865b0a321c.png)

**Comment by pvinis** [comment] 2019-08-06 09:41
Also if I press enter in the script, I get
```
Error detected while processing function OnStdin:
line    4:
E474: Attempt to decode a blank string
Press ENTER or type command to continue
```
but I guess that's alright, since it will exec in the background, without me being able to press enter :p

**Comment by glacambre** [comment] 2019-08-06 09:55
>Also if i add the extra part in the firenvim script it runs with no errors, and it just waits there.

Yup, that's normal, this is because it waits for firefox to write something to its stdin. If you try piping something to it (e.g. `printf 'abcde{"password":"password","origin":"origin"}' | nvim --headless -c ':set rtp+=/Users/pvinis/Source/temp/firenvim' -c 'call firenvim#run()'`), it should reply with a port number.

I've never encountered this BUFFER_SHORTAGE issue. Could you open the page's debugger and place a log point of msg on this line? https://github.com/glacambre/firenvim/blob/8506059d6b67620eba55cd0cf9a13009eaea2074/src/nvimproc/Stdout.ts#L23

**Comment by pvinis** [comment] 2019-08-06 10:09
![Screenshot 2019-08-06 at 12 09 29](https://user-images.githubusercontent.com/100233/62531615-0fdd6d00-b843-11e9-92ef-89b76a25d410.png)
Does that help?

**Comment by pvinis** [comment] 2019-08-06 10:47
and `decoded` is printing
![Screenshot 2019-08-06 at 12 46 52](https://user-images.githubusercontent.com/100233/62533999-4964a700-b848-11e9-9370-fa5a3d6e85cf.png)
which might be the problem? i see its an array once, and its a number before and after that..

**Comment by glacambre** [comment] 2019-08-06 16:58
I'm pretty disappointed to see that there's nothing obviously wrong in these screenshots. Could you add an `uint8arr.toString()` log point here? https://github.com/glacambre/firenvim/blob/8506059d6b67620eba55cd0cf9a13009eaea2074/src/nvimproc/Stdout.ts#L24

This should result in multiple strings of numbers separated by commas being logged to the console. Please upload all of the strings that are logged before the `BUFFER_SHORTAGE` error somewhere (pastebin, gist), this should be enough to help me reproduce your issue and hopefully understand and fix it.

**Comment by pvinis** [comment] 2019-08-07 09:14
It printed 4 times before the shortage error.
first: https://pastebin.com/b2QCpx0Y
second: https://pastebin.com/JE6Limfz
third: https://pastebin.com/wHTfuwk3
fourth: https://pastebin.com/PRp4FYEi

if you prefer a way for faster communication, let me know.

**Comment by pvinis** [comment] 2019-08-07 09:21
I saw https://ourcodeworld.com/articles/read/164/how-to-convert-an-uint8array-to-string-in-javascript on the bottom, it has a way for large blocks. Could that be of help?

**Comment by glacambre** [comment] 2019-08-08 08:56
Thank you for posting this. It looks like concatenating messages is enough to make msgpack-lite stop throwing errors, which probably means that firefox is splitting messages in multiple parts, even if they were sent as a single websocket packet. I didn't expect it to do that and I think I fixed it with #55. Could you try building from master again and see if anything changes?

**Comment by pvinis** [comment] 2019-08-08 08:58
Sure thing. Trying now!

**Comment by pvinis** [comment] 2019-08-08 10:50
I am getting
```
 ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:2822:14
        TS2300: Duplicate identifier 'LibraryManagedAttributes'.

    ERROR in [at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:2823:14
        TS2300: Duplicate identifier 'LibraryManagedAttributes'.

    ERROR in [at-loader] ./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:2937:13
        TS2717: Subsequent property declarations must have the same type.  Property 'td' must be of type 'DetailedHTMLProps<TdHTMLAttributes<HTMLTableDataCellElement>, HTMLTableDataCellElement>', but here has type 'DetailedHTMLProps<TdHTMLAttributes<HTMLTableDataCellElement>, HTMLTableDataCellElement>'.
```
when i run `yarn build` :(

**Comment by glacambre** [comment] 2019-08-08 10:57
Weird, I'm not getting any issues. Could you try rolling "@types/react" back to version 16.8.5 in package.json?

**Comment by pvinis** [comment] 2019-08-08 11:00
Do you have telegram or any discord or something we could talk directly, and we can solve this together? (also, doesn't need to happen now, but i wanna help make this work on mac because i want to use it :D )

**Comment by glacambre** [comment] 2019-08-08 11:03
I try to avoid proprietary software so I'm not on discord/telegram. I do have a matrix account though ( @glacambre:matrix.org ) and if you don't want to install a matrix client you can use [riot.im](riot.im) :).

**Comment by glacambre** [comment] 2019-08-08 11:58
@pvinis confirmed that firenvim is now working on mac, so I'm closing this :)

**Closed by glacambre** 2019-08-08 11:58 UTC

**Comment by nindwen** [comment] 2019-09-27 12:56
The extension doesn't seem to work on Mac for me at least. The border gets drawn around textarea, but it does nothing.  `printf 'abcde{"password":"password","origin":"origin"}' | ./.local/share/firenvim/firenvim`prints version info. No erros on browser console.

**Comment by glacambre** [comment] 2019-09-27 15:56
@nindwen What browser are you using?

**Comment by nindwen** [comment] 2019-09-27 20:48
Firefox.

**Comment by glacambre** [comment] 2019-09-28 15:18
@nindwen Do you get any errors in the background or content consoles? (see [the troubleshooting guide](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-the-browser-extension-can-communicate-with-neovim) in order to find out how to open them).

**Comment by pvinis** [comment] 2019-09-29 15:46
I'll try and report back soon too, I was away from my computer for a few days.

**Comment by pvinis** [comment] 2019-09-30 07:47
Alright, update time. Im writing this using firenvim!

So, like the readme said, I made sure Im nvim 0.4.0+, so I have 0.4.2 from brew. I installed using Plug with `plug 'glacambre'`, then `:PlugInstall`.

After that I ran the command with the headless thing from the readme.

Then I enabled the addon on firefox 70.0b10 (beta).

After I refreshed github and I clicked inside the textarea, now I can use.

**Comment by nindwen** [comment] 2019-10-02 10:06
Sorry, missed the extension console earlier.

This seems to happen every time I click the extension icon, otherwise there's nothing:

![Screenshot 2019-10-02 at 13 04 05](https://user-images.githubusercontent.com/5244699/66036150-3a7f3580-e515-11e9-88eb-e6d9b3fd4fec.png)

**Comment by glacambre** [comment] 2019-10-02 11:36
I don't think these errors are related to your problem (I nonetheless fixed them in 43ed7c13bbf23e6389d5012d2f478010e13509bd). Could you check the browser console? (hamburger menu -> Web Developer -> Browser Console, then empty the console by clicking on the trash icon and try to start a new firenvim instance by clicking on a textarea)

**Comment by nindwen** [comment] 2019-10-02 14:33
It remains empty.

**Comment by glacambre** [comment] 2019-10-02 15:14
This is going to be hard to debug if we're not getting error messages in any of the 3 consoles :/

Could you open the extension/background debugger, search for `if (p.error) {` in either of `background.js` or `background.ts`, place a breakpoint on that line and then switch to the console and run `getNewNeovimInstance().then(console.log).catch(console.log)`?

**Comment by nindwen** [comment] 2019-10-02 15:45
Sorry, I didn't actually have the extension enabled at that time. 😅

Now I can see that neovim fails to load python3. Could this be related to the $PATH problem? Running the suggested install on troubleshooting didn't work though.

```stderr output from native app firenvim: [deoplete] 'python3' is not executable.[deoplete] You need to set g:python3_host_prog.[deoplete] Failed to load python... stderr is available in messages.[deoplete] function remote#defin...quire[13]..provider#Poll, line 14[deoplete] deoplete requires Python3 support("+python3").
stderr output from native app firenvim: Error detected while processing function deoplete#enable[9]..deoplete#initialize[1]..deoplete#init#_initialize[15]..deoplete#init#_channel[38]..deoplete#init#_python_version_check:
stderr output from native app firenvim: line    8:
stderr output from native app firenvim: E319: No "python3" provider found. Run ":checkhealth provider"
```

I can bypass this by setting g:python3_host_prog manually.

After that I get very unhelpful

```
stderr output from native app firenvim: Error detected while processing ~/.vim/plugged/notational-fzf-vim/plugin/notational_fzf.vim:
stderr output from native app firenvim: line   13:
```

Disabling notational_fzf finally makes this work.

**Comment by glacambre** [comment] 2019-10-02 16:42
Great!

>Now I can see that neovim fails to load python3. Could this be related to the $PATH problem?

I think it is, and I believe this might also be the reason you have issues with your fzf plugin.

Could you check if the `export PATH=…` line in `~/.local/share/firenvim/firenvim` exports a `$PATH` identical to the one you have in your shell?
