### ISSUE TITLE
Black box when reviewing on gofreeconcepts

### ISSUE THREAD

**Issue by xeruf** [glacambre/firenvim#1102] opened 2021-08-09 13:53 UTC
- OS Version: linux x86-64
- Browser Version:  Firefox 90.0
- Browser Addon Version: 0.2.7
- Neovim Plugin Version: 0.2.7

### What I tried to do

Write a review for a product from https://gofreeconcepts.de/collections/barfussschuhe-fur-sport-und-outdoor

### What happened

I get a black box:
![image](https://user-images.githubusercontent.com/13354331/128717174-4086ec03-888d-4b22-8699-e6c117f6075c.png)

Maybe related to https://github.com/glacambre/firenvim/issues/145 ?

**Comment by glacambre** [comment] 2021-08-09 16:39
Do you get any messages in the content console? (Visit page -> Open console (`<C-S-i>`) -> Clear messages -> Try to start a Firenvim instance)

**Comment by xeruf** [comment] 2021-08-10 19:46
![image](https://user-images.githubusercontent.com/13354331/128925135-35bd2019-238a-4d55-886e-dee6ae744054.png)

**Comment by glacambre** [comment] 2021-08-11 04:56
This looks like https://github.com/glacambre/firenvim/issues/811 indeed :/

**Comment by glacambre** [comment] 2021-08-25 00:22
Oh, wait, re-reading the warning I think this is https://github.com/glacambre/firenvim/issues/145 ! So it should be fixed in firefox nightly, could you try that and let me know if the problem is fixed?

**Comment by glacambre** [comment] 2021-09-25 18:49
I'm 100% this is fixed on master + neovim nightly.

**Closed** 2021-09-25 18:51 UTC
Labels: host:firefox, webextension-limitation, awaiting-author

**Comment by xeruf** [comment] 2021-09-28 10:10
Indeed fixed, thank you very much :)
