### ISSUE TITLE
How to prevent bottom line scrool to top of the window?

### ISSUE THREAD

**Issue by eval-exec** [glacambre/firenvim#1116] opened 2021-08-17 08:40 UTC
- OS Version: ArchLinux 
- Browser Version:   Google Chrome 92.0.4515.159
- Browser Addon Version: 0.2.7
- Neovim Plugin Version: 

how to prevent buffer's bottom line scroll too top of the text window?

![2021-08-17_16-39](https://user-images.githubusercontent.com/46400566/129693331-707ed334-9526-465d-acd0-fff93d402b1b.png)

**Comment by glacambre** [comment] 2021-08-17 10:18
I can't reproduce this. Could you remove all your settings (except the ones loading the Firenvim plugin) and try to reproduce again?

**Comment by glacambre** [comment] 2021-09-18 12:32
Closing this issue as it has been awaiting an answer for more than a month. If you are still experiencing an issue, please answer the question and I'll re-open :).

**Closed by glacambre** 2021-09-18 12:32 UTC
Labels: awaiting-author, blocked
