### ISSUE TITLE
Allow not showing file name on startup and write

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#351] opened 2020-01-15 05:58 UTC
I think this is something for the UI to do. When using the firenvim command window, on startup and write, the name of the file is displayed across 1-4 lines of the window. Firenvim space is precious, and this is annoying. I tried to get rid of it with various autocmds and `feedkeys`, but no luck.

**Comment by glacambre** [comment] 2020-01-15 06:00
Duplicate of https://github.com/glacambre/firenvim/issues/328, accidentally fixed in https://github.com/glacambre/firenvim/pull/344/files. I just need to publish a new release :)

**Closed by glacambre** 2020-01-15 06:00 UTC

**Comment by BlueDrink9** [comment] 2020-01-15 06:01
You're so good :)
