### ISSUE TITLE
`<C-e>` not working

### ISSUE THREAD

**Issue by TyberiusPrime** [glacambre/firenvim#180] opened 2019-10-28 10:08 UTC
Is there a way to have a 'click to enable' beside the text areas 
so that I can use firenvim on a case by case basis?

**Comment by glacambre** [comment] 2019-10-29 07:06
When you're in an element you want to edit, you can press `<C-e>` in order to ask firenvim to turn that element into a neovim frame. You can configure this shortcut in `chrome://extensions` or `about://addons`. I'm not sure how well a `turn into neovim` context menu entry would work as it can be quite tricky to target the element you want to edit with your mouse.

**Comment by glacambre** [comment] 2019-11-01 10:26
Oh, and if you don't want to have firenvim on by default you can follow the steps described here: https://github.com/glacambre/firenvim#configuring-the-browser-addon-behavior

I'll close this issue because I believe this answers your needs but if it doesn't, feel free to reopen :)

**Comment by TyberiusPrime** [comment] 2019-11-01 11:04
yeah, I can't get the short cut to work, but that's a separate issue.

**Comment by glacambre** [comment] 2019-11-01 19:06
What browser are you using? Do you have any other addon that might interfer with firenvim? Does changing the keyboard shortcut to anything else than `<C-e>` helps?

**Comment by TyberiusPrime** [comment] 2019-11-04 08:20
I'm on opera 64.0.3417.73, ubuntu 18.04,
so it might just be my weird browser.

Extensions enabled:

Adblock Plus - free ad blocker
Emulates Opera 12 tab behaviors
Enpass Password Manager extension for Chrome
Firenvim
Google Translate
I don't care about cookies
Install Chrome Extensions
JavaScript Switcher
Todoist: To-Do list and Task Manager

**Comment by glacambre** [comment] 2019-11-04 19:48
I have no idea why this isn't working, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility says it should. I'd rather avoid installing proprietary software so you'll have to debug this yourself :p
I'd recommend trying a fresh profile first (with only firenvim installed) and see if it changes anything. If it doesn't, I can provide instructions to start debugging firenvim either here or on matrix (there's a firenvim room).

**Comment by glacambre** [comment] 2019-12-19 19:30
I installed opera in a VM and the firenvim shortcut is working fine (I had to manually assign it to `<C-e>` though). How did you install opera (snap, .deb from the opera website, something else?)? Does firenvim work at all? Do you have a specific keyboard layout?

**Comment by TyberiusPrime** [comment] 2019-12-20 08:16
I've reinstalled a newer ubuntu in the mean time, and now the assigned shortcut does work.
But of course, now nvim dies unexpectedly in the background :).

**Comment by glacambre** [comment] 2019-12-20 08:26
>now nvim dies unexpectedly in the background

Thanks for reporting back. I think I know what the problem is, I'll push a fix in ~12 hours :).

**Comment by glacambre** [comment] 2019-12-20 16:39
Did you run the `firenvim#install()` function in neovim? If yes, how did you install opera (snap, .dev from the opera website, something else?)? Do you have google chrome installed on your computer? If yes, do you have a file named `$HOME/.config/google-chrome/NativeMessagingHosts/firenvim.json` on your computer?

**Closed** 2020-01-16 07:31 UTC
Labels: blocked:awaiting-author
