### ISSUE TITLE
Latest version almost impossible to use

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#206] opened 2019-11-05 06:10 UTC
Several things have gone haywire all at once. This morning I updated my distro (Arch) from a machine that had been sitting for a few days, so it now has the latest Firefox (70.0.1) and this plugin for both Firefox and Neovim.

I'm writing this issue from Firenim so I have it kind of working, but it's very touch.

1. When I first started Firefox it wouldn't work at all. I finally found that Neovim was complaining about ShaDa and the error wasn't being passed through to Firenvim. Nuking the ShaDa folder got past that, but this appears to be another instance of #196.

2. The Firenvim icon even in this tab where I'm using it shows up red and says Firenvim is not responding.

3. I can't get _out_ of Firenvim. Closing it drops back to the textarea, but any action (keyboard or mouse) that triggers an event on the textarea fires up Firenvim again. I can't get rid of it.

4. Disabling "on this tab" doesn't stop it from firing up.

Normally I would open separate issues for each symptom, but something tells me these might all be stemming from the same core issue buried somewhere. I don't know what it is, but something went haywire. Where do I even look?

**Comment by glacambre** [comment] 2019-11-05 09:32
> I finally found that Neovim was complaining about ShaDa and the error wasn't being passed through to Firenvim
> The Firenvim icon even in this tab where I'm using it shows up red and says Firenvim is not responding.
These are linked ; I can't actually retrieve neovim's startup errors (the Native Messaging API do not let you read stderr). So when neovim fails to start, I can only tell the user that neovim isn't responsing. If you managed to fix firenvim, using the `reload settings` button should be enough to clear the browser icon.

>I can't get out of Firenvim. 
This sounds like #203. I'm not sure why this suddenly started happening; I'll investigate.

>Disabling "on this tab" doesn't stop it from firing up.
This is really weird.

>Where do I even look?
I'll provide instructions in ~10 hours :).

**Comment by alerque** [comment] 2019-11-05 09:35
I did try the "reload settings", and that did not clear the icon even after Neovim started working again. I've restarted Firefox from a cold start and it is still not cleared as of this writing (which I'm writing in Firenvim).

**Comment by glacambre** [comment] 2019-11-05 11:08
>I can't get out of Firenvim.

I think this happens because of Tridactyl's modeindicator. Temporarily `:set modeindicator false` to work around this.

**Comment by glacambre** [comment] 2019-11-05 11:51
Could you test #206 and let me know if the frame still reappears after you `:wq`'d firenvim?

**Comment by glacambre** [comment] 2019-11-05 20:44
The biggest offender - 3) - should be fixed with #207. I'm sorry I didn't have time to provide instructions to investigate bugs in firenvim, I hope I'll be able to do that tomorrow (although I'm afraid I won't be).

**Comment by glacambre** [comment] 2019-11-10 15:51
I released a new version that should make things usable again - please update and let me know what bugs you can still reproduce.

**Comment by glacambre** [comment] 2019-11-12 20:53
The "disable firenvim in this tab" issue can still be reproduced.

**Comment by glacambre** [comment] 2019-11-18 07:10
I believe I fixed every problem this issue references in v0.1.14, could you update and let me know if you're still encountering problems?

**Comment by masaeedu** [comment] 2019-11-19 22:59
I'm not sure if my browser is affected by the same issues the OP was mentioning, but I installed firenvim today (Firefox 70), and it seems to be working FWIW

**Closed** 2019-11-24 15:00 UTC

**Comment by alerque** [comment] 2019-11-26 05:38
@glacambre I've been out of town (and away from computers) for 8 days. I'm in the process of updating now and will report anything I run into, but even before I left I think Firenvim had become mostly serviceable (and I'm writing this in it now, so it's no longer completely broken!).

Thanks for all the work on this, I still love it.

**Comment by oren** [comment] 2020-01-04 05:05
I just installed firenvim and I see `Neovim is not responding` when I click on the extension's icon. Any workarounds or troubleshooting tips?

(Firefox 71.0, NVIM v0.5.0-dev, Ubuntu 16.04)

**Comment by glacambre** [comment] 2020-01-04 05:44
@oren Did you run `firenvim#install()`? If yes, how did you install firefox? (Apt, snap, flatpak, something else?).

**Comment by oren** [comment] 2020-01-04 06:35
no, I use Plug so I did the following:
1. Added this line to init.vim: `Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }`
1. Closed nvim
1. Opened nvim and run `PlugInstall`

Questions:
* That's what I do to install new plug-ins. Is there a different/better way?
* How do I run `firenvim#install()`?

**Comment by glacambre** [comment] 2020-01-04 06:47
>That's what I do to install new plug-ins. Is there a different/better way?

No, using vimèplug is fine :).

>How do I run firenvim#install()?

Run `:call firenvim#install()` in Neovim. But you don't need to do that, the `Plug …` line did that for you.

How did you install Firefox? This is important because there may be issues with snap and flatpak as they try to sandbox Firefox (and they would thus prevent it from running neovim).

**Comment by oren** [comment] 2020-01-04 07:39
I believe i used `apt-get install firefox` but i can't remember since it was long time ago. I also tried using chrome and got the same message - Neovim is not responding.

**Comment by gcqmkm02** [comment] 2020-06-16 11:44
Moi j'ai le même problème

**Comment by glacambre** [comment] 2020-06-16 16:15
@gcqmkm02 Please open a new issue and describe the problem you are encountering - ouvre un nouveau ticket et décris ton problème s'il te plaît :).
