### ISSUE TITLE
Unicode not (fully) supported?

### ISSUE THREAD

**Issue by Magicrafter13** [glacambre/firenvim#932] opened 2021-02-05 02:14 UTC
- OS Version: Manjaro Linux x64
- Browser Version:  Firefox 85.0
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.2.3
- What happened: Unicode characters don't display (or at least some of them?)

Best example is showing my lightline config, which should have dividers between the colored sections. And a little floppy disk next to the ! (that's how I indicate the file isn't saved).

![firenvim](https://user-images.githubusercontent.com/29127566/106980284-bd6d5d00-6714-11eb-9618-47a92d0a4629.png)

It's weird though, since it *seems* like it's using the same font I use normally in Neovim, and yet I can't see the characters...

**Comment by glacambre** [comment] 2021-02-05 05:14
Are these emojis or powerline symbols?

In both cases, I think the problem is that the font isn't right. You need to find the name of the font that has these glyphs on your computer and then use that with `:set guifont=NAMEOFTHEFONT` to make firenvim use it.

Firenvim can't do any font detection has browsers don't let pages/extensions do that for privacy reasons.

**Comment by Magicrafter13** [comment] 2021-03-11 00:04
Set the font but the glyphs still don't appear.

(The difference is subtle, but you'll notice my font has a dot in the zeroes.)

![fire](https://user-images.githubusercontent.com/29127566/110715539-49622100-81ba-11eb-8b09-acc3c0a0caa4.png)

**Comment by glacambre** [comment] 2021-03-11 04:44
>Set the font but the glyphs still don't appear.

Does the font you've set have these symbols?

**Comment by Magicrafter13** [comment] 2021-03-21 06:28
> > Set the font but the glyphs still don't appear.
> 
> Does the font you've set have these symbols?

It's the only don't I've used for 2-3 months with NeoVim, and my terminal. One if the reasons I chose it was *because* it supported them :)

It's a Nerd Font. Caskaydia Cove to be specific.

**Comment by glacambre** [comment] 2021-03-21 07:13
If I understand https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode/Regular correctly they're only patching a single font file with the symbols and then relying on font-fallback to make them available across the font family. So your issue is probably an instance of https://github.com/glacambre/firenvim/issues/946 .

What `:set guifont=…` value are you using and what are the codepoints that aren't displayed?

**Comment by glacambre** [comment] 2021-04-24 13:09
Closing this issue as it's been awaiting information from the author for more than a month.

Please let me know (and answer my questions ;) ) if you are still experiencing this issue - I'll reopen :).

**Closed by glacambre** 2021-04-24 13:09 UTC
Labels: awaiting-author, blocked

**Comment by Magicrafter13** [comment] 2021-05-04 08:14
Well... I don't remember what I did before, but it worked tonight! And yeah, massive RIP for how long I go without responding to these... sorry.

`set guifont=CaskaydiaCove\ Nerd\ Font\ Mono` (works without mono but spacing is a little off, which makes sense)

![fire](https://user-images.githubusercontent.com/29127566/116976407-f2d30980-ac75-11eb-8280-102bac7176d3.png)

I wish those block characters looked nicer, but I've seen this happen in several terminals so I won't blame that on this plugin.

**Comment by glacambre** [comment] 2021-05-04 11:22
Good to hear that the problem is fixed :).

>I wish those block characters looked nicer, but I've seen this happen in several terminals so I won't blame that on this plugin.

You could try adjusting linespace (e.g. `:set linespace=-3`), but I don't recommend fiddling with that setting.
