### ISSUE TITLE
Useless text "the only match" in external commandline

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#634] opened 2020-07-08 09:44 UTC
- OS Version: linux x86-64
- Browser Version:  Firefox 78.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do: Use the external commandline to optimize space usage
- What happened: Often, a little text "the only match" appears in the bottom right, and if I type out the exact suggested word it stays there until another suggestion is made. Sometimes the box content also changes to only a ">", idk what's happening.

![image](https://user-images.githubusercontent.com/13354331/86903798-1db10780-c110-11ea-96a5-725a03361b51.png)

Maybe I have to configure the suggestions differently or something?

**Comment by glacambre** [comment] 2020-07-09 04:13
Yes, `The only match` comes from your completion plugin (deoplete I believe?). The lingering of these messages (including the angle bracket) is caused by https://github.com/neovim/neovim/issues/11558 .

**Comment by glacambre** [comment] 2020-07-09 04:15
Closing in favour of https://github.com/glacambre/firenvim/issues/448 :)

**Closed by glacambre** 2020-07-09 04:15 UTC
Labels: blocked:neovim-feature, blocked:other-issue

**Comment by xerus2000** [comment] 2020-07-09 11:01
Actually, as far as I'm aware, I use no completion plugin :thinking: 

This is my list of plugins:
```vim
" Plug
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

" Editing
 " text objects
Plug 'xerus2000/argtextobj.vim' " arguments in brackets as text objects
Plug 'tpope/vim-surround'       " edit surroundings - cs, ds, ys
Plug 'bkad/CamelCaseMotion'     " move through camel case words
 " commands
Plug 'inkarkat/vim-ReplaceWithRegister' " gr to replace with register
Plug 'tpope/vim-commentary'             " gc to comment out (gcap for paragraph)
Plug 'terryma/vim-multiple-cursors'     " <C-n> new coursor+selection on match, <C-x> skip, <C-p> remove cursor & back
Plug 'junegunn/vim-easy-align'          " ga to align stuff
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
 " libs
Plug 'tpope/vim-repeat'
Plug 'inkarkat/vim-ingo-library'

" Ex commands
Plug 'DataWraith/auto_mkdir'     " mkdir parent dirs when saving
Plug 'AndrewRadev/bufferize.vim' " Command to buffer
Plug 'tpope/vim-eunuch'          " OS helpers
Plug 'tpope/vim-fugitive'        " Git commands in vim
Plug 'jreybert/vimagit'          " Magit for vim - git stage individual changes
Plug 'doy/vim-diff-changes'      " Commands for diffing - :DiffAgainstFilesystem :DiffAgainstVCS :DiffStop
Plug 'junegunn/fzf'              " File selection with :FZF
 " Browse
Plug 'tyru/open-browser.vim' " :OpenBrowser, :OpenBrowserSearch
Plug 'tyru/open-browser-github.vim'

" QOL
Plug 'farmergreg/vim-lastplace' " Automatically jump to last edit position
Plug 'chrisbra/Recover.vim' " Add Recover options for swap files
Plug 'ntpeters/vim-better-whitespace' " Tools for trailing whitespace & mixed indents

" Aesthetic
Plug 'vim-airline/vim-airline' " Status bar on the bottom
Plug 'psliwka/vim-smoothie' " Smooth scrolling
Plug 'romainl/vim-cool' " Automatically stop highlighting search results when moving - https://stackoverflow.com/questions/657447/vim-clear-last-search-highlighting
Plug 'airblade/vim-gitgutter' " Git info on the left
Plug 'norcalli/nvim-colorizer.lua' " Highlights color literals
 " Visual indent guides
Plug 'nathanaelkane/vim-indent-guides'
let g:indent_guides_enable_on_vim_startup = 1

" Integrations
Plug 'xerus2000/vim-dokuwiki'
Plug 'neoclide/coc.nvim', {'branch': 'release' }
Plug 'udalov/kotlin-vim'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }

call plug#end()
```

**Comment by glacambre** [comment] 2020-07-09 11:53
Doesn't coc.nvim do completion?

**Comment by xerus2000** [comment] 2020-07-09 12:13
I thought it would just be a sort of library for language-specific stuff, but I'm not sure tbh.

**Comment by glacambre** [comment] 2020-07-09 16:50
CoC stands for [Conquer of Completion](https://github.com/neoclide/coc.nvim/), so I'm almost certain it's a completion engine :)

**Comment by xerus2000** [comment] 2020-07-09 18:53
Oh wow, never looked it up, was recommended by a friend :sweat_smile:
