### ISSUE TITLE
Completely broken in OpenStreetMap Changeset comment

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#607] opened 2020-06-18 08:07 UTC
![image](https://user-images.githubusercontent.com/13354331/84994564-2636a380-b14b-11ea-836b-ffa0eba99eac.png)

Firenvim works fine for me mostly, but in this textbox it completely broke: It appeared there, but then didn't react to any keypresses, even after I explicitly focused it again. I can't even close it!

- OS Version: linux x86-64
- Browser Version:  Firefox 77.0
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27

**Comment by alerque** [comment] 2020-06-18 08:19
There are several different OSM editors and forms to post changesets. It isn't immediately apparent which editing system you are using or what form you ended up on. It would be helpful if you provided more detail like a URL for the page with the editor.

**Comment by xerus2000** [comment] 2020-06-18 14:02
Right, I used iD, it is the form after clicking the save button to add the changeset comment.

**Comment by alerque** [comment] 2020-06-18 14:50
Confirmed, I was able to replicate this. The input doesn't look too different to me although it does have some Javascript validation checks attached. Not being able to focus the Firenvim input is a new one to me.

**Comment by glacambre** [comment] 2020-06-19 07:10
Took me a while to figure out, this happens because the page contains multiple frames. Basically you have one firenvim process per frame and they have to communicate with each other via message passing. The webextension APIs do not make this easy - so what I'm doing is rather error prone. I have a local fix - I'll write a test and merge it today or tomorrow.

**Comment by xerus2000** [comment] 2020-06-19 08:35
Thanks :)

**Comment by glacambre** [comment] 2020-06-20 06:52
This is now fixed in master. I'll publish a new addon release tomorrow or on monday :).

**Closed by glacambre** 2020-06-20 06:52 UTC

**Comment by xerus2000** [comment] 2020-07-08 10:53
Thank you, works great!
