### ISSUE TITLE
Broken on all stackexchange sites

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#735] opened 2020-10-16 19:36 UTC
Whether it's https://stackoverflow.com/questions/ask or emacs stackexchange, whenever I press into the question compose box, it shortly flickers and I am left with nothing. The text field isn't editable, but nvim has also not appeared. It still works here on github though...

Disabling for the tab allows me to at least compose something there, but that's not a solution...

- OS Version: linux x86-64
- Browser Version:  Firefox 81.0
- Browser Addon Version: 0.1.31
- Neovim Plugin Version: 0.1.31

**Comment by xerus2000** [comment] 2020-10-16 19:39
<img width="948" alt="image" src="https://user-images.githubusercontent.com/13354331/96301797-024f7580-0ff8-11eb-94a2-7226352fef0c.png">
maybe this helps

**Comment by alerque** [comment] 2020-10-16 19:49
This is a duplicate of #145.

**Comment by glacambre** [comment] 2020-10-17 04:06
alerque is right, this is a duplicate of #145. I still plan on fixing it some day, but it won't be anytime soon as delving in Firefox's code is a huge time investment.

>emacs stackexchange

That's disgusting, don't ever tell people you visit websites like that ;)

**Closed by glacambre** 2020-10-17 04:06 UTC
