### ISSUE TITLE
Chrome <C-t>, <C-n>, <C-w> emulation doesn't work with v0.1.28

### ISSUE THREAD

**Issue by andrey-bolduzev** [glacambre/firenvim#611] opened 2020-06-22 14:12 UTC
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 83.0.4103.106
- Browser Addon Version: 0.1.28
- Neovim Plugin Version: 0.1.28
- What happened:

After upgrading to v0.1.28 Chrome plugin version, the `<C-t>`, `<C-n>`, `<C-w>` key presses are being swallowed without having any effect.

The forwarding is set up in the Chrome keyboard shortcuts. Downgrading to Chrome plugin v0.1.27 fixes the issue.

**Comment by glacambre** [comment] 2020-06-22 17:10
Thanks for the report. This bug was introduced in 
https://github.com/glacambre/firenvim/pull/609 and should be easy to 
fix, I should be able to release an updated version tomorrow. This 
regression went unnoticed because there aren't any APIs to test browser 
shortcuts, I'll have to think about finding a way to work around this.

**Comment by andrey-bolduzev** [comment] 2020-06-22 17:11
> Thanks for the report. This bug was introduced in #609 and should be easy to fix, I should be able to release an updated version tomorrow. This regression went unnoticed because there aren't any APIs to test browser shortcuts, I'll have to think about finding a way to work around this.

Thank you for your work!

**Comment by coordinatio** [comment] 2020-06-23 08:59
"Turn the currently focused element into a neovim iframe." shortcut on Firefox does not work with v.0.1.28 either. Downgrading the addon to v.0.1.27 helps. Seems like the same issue to me.

OS Version: linux x86-64
Browser Version: Mozilla Firefox 77.0.1
Browser Addon Version: 0.1.28
Neovim Plugin Version: 0.1.28

**Comment by glacambre** [comment] 2020-06-24 04:48
This is fixed on master. I submitted a new version for release on Chrome, it should be available soon. However I can't submit a new version for Firefox - there's a bug in their addon submission process ( https://github.com/mozilla/eslint-plugin-no-unsanitized/issues/138 ).

**Comment by glacambre** [comment] 2020-06-24 05:18
The issue preventing me from uploading a new version to Mozilla's addon store is gone, so I have been able to submit a new version for review, which has been accepted.

Unfortunately you'll need to restart your browser in order to be able to update to a new Firenvim version. This is because Firenvim detects if there are neovim instances running and avoids updating to prevent losing your work - the bug you reported breaks that.

Again, thanks for the bug report, and sorry for breaking things :)

**Closed by glacambre** 2020-06-24 05:18 UTC
