### ISSUE TITLE
Fzf-Lua doesn't let firenvim load

### ISSUE THREAD

**Issue by VanshajSaxena** [glacambre/firenvim#1656] opened 2024-12-24 19:29 UTC
- OS Version: NixOS: 24.11 built using flakes.
- Browser Version: Firefox v133.0.3 (64-bit)
- Browser Addon Version: 0.2.16
- Neovim Plugin Version: This commit [dd2d6f6](https://github.com/glacambre/firenvim/commit/dd2d6f6)

### What I tried to do

Launch Firenvim with the browser shortcut.

### What happened
Didn't load, shows a blank box, freezes itself.
Like this.
![Screenshot_20241225_005004](https://github.com/user-attachments/assets/c2d68e68-1236-42c8-b879-7da74a08eb17)

### Additional Context
The issue first arose when I switched to [fzf-lua](https://github.com/ibhagwan/fzf-lua) as the default fuzzy finder. This happened after  [LazyVim](https://github.com/LazyVim/LazyVim) defaulted to fzf-lua.
Ever since the switch over to fzf-lua by default, Firenvim broke for some reason. And it shows this error.
![Screenshot_20241225_002750](https://github.com/user-attachments/assets/bba1ec06-3006-4757-bdf8-2222207e4652)

Here is the config I use on top of LazyVim:
```
 {
    "glacambre/firenvim", -- Firenvim for browser integration
    lazy = not vim.g.started_by_firenvim,
    build = function()
      require("lazy").load({ plugins = { "firenvim" }, wait = true })
      vim.fn["firenvim#install"](0)
    end,
 }
 {
    "ibhagwan/fzf-lua",

    opts = {
      winopts = {
        preview = {
          delay = 10,
        },
      },
    },
 },
```

**Comment by glacambre** [comment] 2024-12-24 20:30
Hi, this sounds like an issue with fzf-lua or lazyvim, not with Firenvim itself, so I'm afraid there's nothing I can do. I'll close this issue but feel free to ask more specific questions if you have any.

**Closed by glacambre** 2024-12-24 20:30 UTC

**Comment by ibhagwan** [comment] 2024-12-27 05:38
@glacambre, see https://github.com/ibhagwan/fzf-lua/issues/1639#issuecomment-2563337008.

firenvim seems to mess up the loading order of files in fzf-lua or not store global vars properly (unsure which of the two happens as I’m deducing this by code route troubleshooting).

In addition, it seems that `nvim_list_uis()` is also not working as expected, in order to get to the error described in the OP the below must return 0 whereas it should return 1 (the attached UI):
```lua
:= #vim.api.nvim_list_uis()
```

**Comment by glacambre** [comment] 2024-12-27 08:53
@ibhagwan Firenvim doesn't do any magic with plugin loading - if there's a problem, it likely comes from the user choosing to load (or not load) plugins depending on whether Neovim was started Firenvim.

`nvim_list_uis` returning 0 is expected: firenvim starts neovim in headless mode first, and only connects a UI when the user clicks on a textarea in their browser. The command firenvim uses to run neovim can be found in `~/.local/share/firenvim/firenvim` and more or less looks like this:
```shell
nvim --headless --cmd ... --cmd ... -c 'call firenvim#run()'
```
Please don't hesitate to ask more questions :)

**Comment by ibhagwan** [comment] 2024-12-27 14:39
Ty @glacambre for the prompt response :)

> nvim_list_uis returning 0 is expected: firenvim starts neovim in headless mode first, and only connects a UI when the user clicks on a textarea in their browser. The command firenvim uses to run neovim can be found in ~/.local/share/firenvim/firenvim and more or less looks like this:

Understood

> @ibhagwan Firenvim doesn't do any magic with plugin loading - if there's a problem, it likely comes from the user choosing to load (or not load) plugins depending on whether Neovim was started by Firenvim.

This is still very odd as the condition causing this error can only happen under two conditions:
1. Running headless (which you confirmed)
2. Loading `fzf-lua/lua/libuv.lua` before `fzf-lua/lua/init.lua`.

In this case, the issue would need to come from @VanshajSaxena config.

@VanshajSaxena, can you link your config and also search for all `require('fzf-lua')` statements and see if you have any that contain a specific module like `require('fzf-lua.xxx')` (perhaps in LazyVim)?

Avoiding the error should be rather easy by lazy loading fzf-lua instead of loading at init, can you try setting fzf-lua to lazy load by adding `cmd = 'FzfLua'` to your lazy config and after firenvim is loaded try running `:FzfLua`?
