### ISSUE TITLE
Adjusting settings for more visible viewing area?

### ISSUE THREAD

**Issue by MostHated** [glacambre/firenvim#1521] opened 2023-03-11 21:18 UTC
Hey there, I was wondering if there was an easy way to resolve my viewing area issue? In the screenshot below, I went to do a reply on twitter, but unfortunately, only about 1/3-1/4 of the input box ends up being actually viewable. 

The arrow is where my cursor is, and the highlighted area is all that is actually visible of what I was typing. All said and done, neither the top nor right side need to be there showing me a temporary filename. I don't really see a need for it that I can think of.
Is this something that needs to be adjusted within Firenvim's settings, or is this something I have to try and work out myself via the g.started_by_firenvim bool and then making general nvim ui adjustments?

The area is so small to begin with, I am wondering if I should just disable it for that site in genenral. I would at least like to see if I can resolve this first and see how it works out.

![](https://img.instance.id/tfrrI8gMPOBS/direct)

Thanks,
-MH

**Comment by glacambre** [comment] 2023-03-11 21:25
Hi, unfortunately there is no real solution, this problem is currently caused by an issue with Neovim's UI protocol ( https://github.com/neovim/neovim/issues/11558 ).

There are two workarounds though:
- pressing `:`, which should open the command line and clear the message area
- reduce your [`cmdlineTimeout`](https://github.com/glacambre/firenvim#configuring-message-timeout) setting to something very short (e.g. 100ms), so that the message area gets cleared as soon as the cursor moves.

I'm going to close this issue because I think there's nothing to do for me here, but feel free to ask more questions if you have them :)

**Closed by glacambre** 2023-03-11 21:25 UTC

**Comment by MostHated** [comment] 2023-03-11 21:58
Not a problem, I had a feeling that it was more of a "going to have to deal with it" kind of thing, but I figured it was worth a shot. I will give those things you mentioned a try, though, but it sounds like my best bet is to just disable it on that site.

**Comment by justinmk** [comment] 2023-03-11 23:04
Is it not feasible for firenvim to "force" a giant textbox on the webpage? Having a bigger editing area is something I often wish for.

**Comment by glacambre** [comment] 2023-03-12 06:53
You can use something like
```
vim.api.nvim_create_autocmd({'UIEnter'}, {
    callback = function(event)
        local client = vim.api.nvim_get_chan_info(vim.v.event.chan).client
        if client ~= nil and client.name == "Firenvim" then
            if vim.o.lines < 4 then
                vim.o.lines = 4
            end
            if vim.o.columns < 80 then
                vim.o.columns = 80
            end
        end
    end
})
```
Firenvim attaches the UI before opening the textarea's buffer, so you can't currently choose a size based on the buffer's name (= page you're using), but I think this could be changed.
