### ISSUE TITLE
Trying to set minimum size of neovim panel

### ISSUE THREAD

**Issue by larsks** [glacambre/firenvim#1425] opened 2022-09-14 15:29 UTC
- OS Version: Fedora 36
- Browser Version: Brave (`Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)`)
- Browser Addon Version: 0.2.13
- Neovim Plugin Version: 56a49d7

### What I tried to do

I am trying to establish a minimum height for the firenvim panel. I tried this:

```
if exists('g:started_by_firenvim')
    function! AdjustMinimumLines() abort
            if &lines < 10
                set lines=10
            endif
    endfunction

    function! OnUIEnter(event) abort
        if 'Firenvim' ==# get(get(nvim_get_chan_info(a:event.chan), 'client', {}), 'name', '')
            set laststatus=0
            set guifont=monospace:h12

            call AdjustMinimumLines()
        endif
    endfunction

    autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
endif
```

### What happened

When called explicitly (`:call AdjustMinimumLines()`), the `AdjustMinimumLines` function operates as intended and adjusts the size of the firenvim panel if it is smaller than 10 lines.

The `OnUIEnter` function is clearly running when entering a textarea (`laststatus` and `guifont` get set as expected), and while `OnUIEnter` is clearly calling `AdjustMinimumLines` (if I put `set` statements there they are executed), it doesn't successfully set the size of the panel.

What am I doing wrong?

**Comment by glacambre** [comment] 2022-09-15 04:22
>What am I doing wrong?

Unfortunately you are not doing anything wrong, the problem is that Neovim's current UI protocol prevents UIs from handling the case of setting font size and window dimensions at the same time (I talk about this in deeper depth in https://github.com/glacambre/firenvim/issues/800#issuecomment-757501541 ). One workaround is to delay setting the size of the font, like suggested here: https://github.com/glacambre/firenvim/issues/1006#issuecomment-1126785734 .

I'll close this issue because there is more information in #800, but thank you for writing a detailed issue along with a reproducer, I appreciate it a lot :).

**Closed** 2022-09-15 04:23 UTC
