### ISSUE TITLE
Firenvim can be activated in a Youtube video (and can then break it)

### ISSUE THREAD

**Issue by Louis-dM** [glacambre/firenvim#1304] opened 2022-02-01 21:10 UTC
This bug is a bit silly and will likely not affect many people, but thought it might be worth reporting anyway.

Firenvim can be activated in Youtube *videos*. Not the comment inpux box, but the actual video. If anything is saved, this causes the video to break, and even breaks other videos if you navigate to them through the recommendations panel at the side of the page.

- OS Version: Fedora 35
- Browser Version: Firefox 96.0
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: latest (not sure which version number it is, but I just ran PlugUpdate and the bug still happens)

### Steps to reproduce
1. Set up firenvim to not activate automatically, and to instead open when prompted with a keyboard shortcut. In my localSettings, `'takeover'` is set to `'never'` (see init.vim below) and I have set `Ctrl+q` to activate firenvim.
2. Open a Youtube video
3. Make sure the video was in focus (by clicking the video, or by clicking in the bottom bar)
4. Press the keyboard shortcut to start firenvim (in my case `Ctrl+q`)

### init.vim
(relevant lines only, remaps etc removed)
```
(removed)

if exists('g:started_by_firenvim')
	
	let g:firenvim_config = {
	    \ 'globalSettings': {
	        \ 'alt': 'all',
	    \  },
	    \ 'localSettings': {
	        \ '.*': {
	            \ 'cmdline': 'neovim',
	            \ 'content': 'text',
	            \ 'priority': 0,
	            \ 'selector': 'textarea',
	            \ 'takeover': 'never',
	        \ },
	    \ }
	\ }
	
	(removed)

endif

(removed)
```

### What happened
Firenvim opens a neovim window with the timestamp as the text. If anything is saved with `:w` before quitting with `:q` then the video is replaced with the text. Clicking where video once was will play/pause the audio as normal, but the video will not be visible. 

### Other observations
Navigating to another video doesn't help; whatever text was saved shows up over those videos too. However, a simple refresh will fix it.

**Comment by glacambre** [comment] 2022-02-02 05:40
This is not a bug but a feature :)

Firenvim allows you to edit any focusable element. For example, go to [example.org](https://example.org/), press `<Tab>` until the `More information...` link is focused and then press `<C-e>`. You'll see firenvim open and you'll be able to replace the text of the link.
If you set the [content](https://github.com/glacambre/firenvim#editing-html-directly) setting to HTML, you'll even be able to edit the element's content as HTML, meaning that if you replace `More information...` with `<h1>Hello World!</h1>`, you'll get a clickable title.

I'll close this issue but feel free to ask any other question you may have :)

**Closed** 2022-02-02 05:40 UTC
