### ISSUE TITLE
Font rendered very blurry -- maybe scaling issue?

### ISSUE THREAD

**Issue by WhyNotHugo** [glacambre/firenvim#1124] opened 2021-08-23 16:20 UTC
- OS Version: linux x86-64
- Browser Version:  Firefox 91.0
- Browser Addon Version: 0.2.8
- Neovim Plugin Version: master 97f4794ffea6c559b71341597a293fe65863c3da 

### What I tried to do

Using firenvim on Linux (with desktop scaling to 1.5x, which I suspect must be related).

### What happened

Text renders very blurry **and** very large. The blurriness is a bit hard to compare due to how screenshots get compressed:

![2021-08-23T18:02:54,220358387+02:00](https://user-images.githubusercontent.com/730811/130480558-d66dd1e3-0408-4728-974a-9391aa95ef57.png)

Firefox+firenvim on the left, neovim on alacritty with font size 11 on the right.

I also noticed that the command bar is misaligned, which is what actually makes me thing this might be related to desktop scaling somehow.

![2021-08-23T18:04:45,173076789+02:00](https://user-images.githubusercontent.com/730811/130480595-e74d2f77-d817-43e9-b38f-31df1ff51a81.png)

**Comment by glacambre** [comment] 2021-08-23 17:40
Yep, that does sound like a scaling issue - very probably the same as #972 and #869.

Problem is, I can't reproduce it, so I can't fix it :/.

>I also noticed that the command bar is misaligned

The command bar is vertically and horizontally centered, that's why it doesn't necessarily align with the grid. I think it's great that way - it makes the fact that it's a separate UI element obvious.

**Comment by WhyNotHugo** [comment] 2021-08-23 20:40
What desktop are you using? You should be able to run `sway` (a wayland compositor) nested inside another X11 or Wayland session on Linux. Not sure about other platforms.

**Comment by WhyNotHugo** [comment] 2021-08-23 20:41
Oh, I though the command bar would be aligned to the bottom as in regular neovim. Why does it get centred?

**Comment by glacambre** [comment] 2021-08-24 04:25
>You should be able to run sway (a wayland compositor) nested inside another X11 or Wayland session on Linux. Not sure about other platforms.

Yes, I am running sway. Changing the scale of a screen (`sway output VGA-1 scale 1`) makes everything blurry on my computer, not just firenvim. So I'm not experiencing the same issue as you are and can't fix yours.

>Oh, I though the command bar would be aligned to the bottom as in regular neovim. Why does it get centred?

Neovim's UI protocol lets UIs decide whether they want to render the command line themselves or let Neovim do it. By default, Firenvim renders the command line itself as this saves a line of screen estate, which is important because the textareas Firenvim operates on are frequently just a few lines tall. If you would rather have neovim render the command line, set the [cmdline setting](https://github.com/glacambre/firenvim#using-the-external-command-line) to `neovim`.

**Comment by WhyNotHugo** [comment] 2021-08-24 10:06
Scale `1.5` will render XWayland apps blurry (but native apps should not be terrible, "it depends").

Can you try `scale 2`? That should be nice and sharp.

**Comment by glacambre** [comment] 2021-08-24 10:17
`scale 2` is sharp for both firefox and firenvim on my computer.

**Comment by glacambre** [comment] 2022-07-17 07:34
This issue probably has been fixed by the merge of #1385. Let me know if the problem persists and I'll re-open.

**Closed by glacambre** 2022-07-17 07:34 UTC
Labels: host:firefox, blocked, cant-reproduce

**Comment by WhyNotHugo** [comment] 2022-07-17 10:18
#1385 sounds like it's a fix for the issue. I'll set up firenvim again and give it a shot.
