### ISSUE TITLE
[bug] cannot imap `<` (or `<lt>`)

### ISSUE THREAD

**Issue by Freed-Wu** [glacambre/firenvim#1238] opened 2021-11-10 14:58 UTC
- OS Version: 5.14.16
- Browser Version:  Firefox 94.0.1
- Browser Addon Version: 0.2.10
- Neovim Plugin Version: 0.2.10

### Reproduce Procedures

```vim
imapclear
imap < aaa<Esc>
# or
imap <lt> aaa<Esc>
```

Press `<`, a `<` will be input, not `aaa`

However,

```vim
imapclear
imap > aaa<Esc>
```

can work normally.

I think it is so weird.

Thanks!

**Comment by glacambre** [comment] 2021-11-10 15:19
Hi, thanks for the report. I can't reproduce this issue - what happens when you enter insert mode, press <C-v> and then <LT> ?
-- 
Ghjuvan Lacambre

**Comment by Freed-Wu** [comment] 2021-11-10 15:48
OMG, When I press `<C-v><lt>`, it will input `<S-lt>` not `<`!

**Comment by glacambre** [comment] 2021-11-10 16:26
Great, thanks for trying this out. What keyboard layout are you using? Does it force you to press shift?

**Comment by Freed-Wu** [comment] 2021-11-10 17:02
I use kitty and gnome-terminal. But I doubt it maybe is not related to terminal emulators...

**Comment by Freed-Wu** [comment] 2021-11-10 17:06
I use en_us. When I use neovim in my terminal (text tty or X11 terminal emulator) , press `<C-V><lt>` will input `<`, it works normal. In firefox browser, press `<C-V><lt>` will input `<S-lt>`

**Comment by glacambre** [comment] 2021-11-11 06:05
Okay. This is a known issue with browsers: they don't provide enough information to let browser extensions know what key the user really wanted to press. There is unfortunately nothing I can do about this :/. Fortunately you can work around it by doing something like `:map <S-lt> <lt>`.

I'll close this issue because there's already https://github.com/glacambre/firenvim/issues/640 about this problem, but thank you for reporting it :).

**Closed by glacambre** 2021-11-11 06:05 UTC
