### ISSUE TITLE
Firenvim fully screen in `leetcode.com`

### ISSUE THREAD

**Issue by tabris233** [glacambre/firenvim#955] opened 2021-02-19 04:27 UTC
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 88.0.4324.182
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do:
     So sorry, I don't know what I can do.
- What happened:
    firenvim work fine in `github.com`/`codeforces.com`/`...`,  but work not fine in  `leetcode.com` .
    look like fully screen in `leetcode.com`

github.com:
![image](https://user-images.githubusercontent.com/29500388/108457060-be71c300-72ac-11eb-9632-40b0294f98b5.png)
codeforces.com
![image](https://user-images.githubusercontent.com/29500388/108457074-c5003a80-72ac-11eb-9080-6677ce12f786.png)
leetcode.com
![image](https://user-images.githubusercontent.com/29500388/108456899-5fac4980-72ac-11eb-87c6-c286e535b3eb.png)

**Comment by tabris233** [comment] 2021-02-19 08:33
i find again

it's my company inner website:
![image](https://user-images.githubusercontent.com/29500388/108478844-fb02e600-72cf-11eb-87be-c5c02a9bd8e1.png)

`http://www.bejson.com/json/format/`
![image](https://user-images.githubusercontent.com/29500388/108478987-21c11c80-72d0-11eb-9584-095d544fec53.png)

**Comment by devanshuDesai** [comment] 2021-03-21 08:29
This issue resolves itself if you take a second to resize the window. Not ideal but it gets the job done. Not sure what's causing this issue.

**Comment by glacambre** [comment] 2021-03-21 08:56
Do you mean the browser window or the neovim window with `:set lines=20 columns=80`?

**Comment by devanshuDesai** [comment] 2021-03-21 10:05
Sorry I should've been more clear. I meant the browser window. I haven't tried resizing the neovim window.

**Comment by glacambre** [comment] 2021-03-21 10:06
No problem, that's useful information, thanks for mentioning it :).

**Comment by glacambre** [comment] 2021-03-27 16:02
@tabris123 @devanshuDesai are you still experiencing this issue? I can't reproduce either on chrome or firefox.

**Comment by tabris233** [comment] 2021-04-04 16:58
> @tabris233 @devanshuDesai are you still experiencing this issue? I can't reproduce either on chrome or firefox.

I can's reproduce, too. 😕

**Comment by glacambre** [comment] 2021-04-04 17:09
@tabris233 That's great news, thank you for checking. I'll close this issue, but feel free to re-open it if the bug comes back :).

**Comment by devanshuDesai** [comment] 2021-04-04 22:09
Yes, I'm still experiencing the issue!

[Here's a clip of what it looks like](https://streamable.com/aok4k6)

**Comment by glacambre** [comment] 2021-04-05 05:08
@devanshuDesai Are all these size changes happening by themselves, without any input from you?

**Comment by devanshuDesai** [comment] 2021-04-05 06:16
The initial expansion of the window is happening by itself. Then, I am resizing the browser window by dragging its edge with my cursor and it automatically fixes the the iframe size. On second thought, this might be related to another issue #972 
I used the fix suggested there by adding `:set guifont=Fira_Code:h20` to my `init.vim` and this is what caused my iframes to become oversized. 

This is what I mean:

**With** `:set guifont=Fira_Code:h20`
![With set guifont](https://user-images.githubusercontent.com/37163544/113543458-4ed54000-959b-11eb-991e-411997ea00c4.png)

**Without** `:set guifont=Fira_Code:h20`
![Without set guifont](https://user-images.githubusercontent.com/37163544/113543126-98715b00-959a-11eb-9ce7-dd9b4d2547d5.png)

Seems like I'm trading off between a readable font size and a manageable iframe size.

**Comment by glacambre** [comment] 2021-04-05 06:32
@devanshuDesai I don't understand why guifont is resizing the frame for you - it doesn't happen for me (see video). I've opened #1006 for your issue.

https://user-images.githubusercontent.com/11534587/113544866-61766600-95e9-11eb-81e6-b9152f9e1dc3.mp4

**Comment by glacambre** [comment] 2021-04-05 06:34
Closing this as the problem isn't leetcode but guifont.

**Closed by glacambre** 2021-04-05 06:34 UTC
Labels: blocked, cant-reproduce
