### ISSUE TITLE
Add support for github edit page

### ISSUE THREAD

**Issue by charlie39** [glacambre/firenvim#1406] opened 2022-08-11 14:53 UTC
Having nvim support in github edit is the real deal.
Or is it supported already and i haven't figured it out?

AFAIK, github edit pages are also textarea but it doesn't work ( at least for me).

**Comment by charlie39** [comment] 2022-08-11 15:50
dang!, so no cigar?

**Comment by glacambre** [comment] 2022-08-11 17:00
Closing as duplicate of #1274, since it contains more information :).

**Closed by glacambre** 2022-08-11 17:00 UTC
