### ISSUE TITLE
Wrong colours on different colour text

### ISSUE THREAD

**Issue by NilsIrl** [glacambre/firenvim#422] opened 2020-02-16 02:21 UTC
- OS Version: linux x86-64 (NixOS)
- Browser Version:  Firefox 72.0.2
- Browser Addon Version: 0.1.20
- Neovim Plugin Version: master

Colour identifiers are highlighted using the plugin: https://github.com/norcalli/nvim-colorizer.lua

And in nvim the highlight is as follows:

![image](https://user-images.githubusercontent.com/26231126/74598090-d8a60f00-5062-11ea-860d-f5e9584386ba.png)

- What happened:

![image](https://user-images.githubusercontent.com/26231126/74598093-ec517580-5062-11ea-830b-53567371b64d.png)

note: The screenshot of firenvim is a bit darker because firenvim wasn't focused.

**Comment by glacambre** [comment] 2020-02-16 05:43
I can't reproduce this. What filetype are you using? What's your colorscheme? What's your `bg` setting set to? What's the content of the buffer?

**Comment by NilsIrl** [comment] 2020-02-16 05:50
> I can't reproduce this. What filetype are you using?

```vim
colorscheme default " To make sure it doesn't impact the rest
set ft=text
norm iGold 
```

**Comment by glacambre** [comment] 2020-02-16 06:01
Still can't reproduce. Could you
```sh
git clone https://github.com/norcalli/nvim-colorizer.lua /tmp/nvim-colorizer.lua
git clone https://github.com/glacambre/firenvim /tmp/firenvim
```
And then write this to `/tmp/init.vim`:
```vim
set rtp+=/tmp/firenvim
colorscheme default
set termguicolors
set bg=dark
set ft=text
set rtp+=/tmp/nvim-colorizer.lua
lua require'colorizer'.setup()
```
And finally, edit `~/.local/share/firenvim/firenvim` to add `-u /tmp/init.vim` to the line that execs Neovim and see if you can still reproduce the problem?

**Comment by NilsIrl** [comment] 2020-02-16 16:29
I can confirm the issue and it isn't a problem of what colour it is set to:

Firenvim:

![image](https://user-images.githubusercontent.com/26231126/74608484-5c9ade00-50d9-11ea-82cd-802ec5112f49.png)

nvim:

![image](https://user-images.githubusercontent.com/26231126/74608488-64f31900-50d9-11ea-8a62-408491c3091d.png)

As you can see, both are set to a black background.

**Comment by glacambre** [comment] 2020-02-16 17:38
I actually could reproduce the issue - I just wasn't looking for the right problem, sorry for being thick.

This is now fixed in master, thank you for reporting this bug :)

**Closed** 2020-02-16 17:37 UTC
