### ISSUE TITLE
Set spell has no visual effect?

### ISSUE THREAD

**Issue by benlieb** [glacambre/firenvim#797] opened 2020-11-22 08:39 UTC
I'm trying to get the expected UI visual for a mispelled word, but there is none. I've triple-checked, and `set spell` is on.

![image](https://user-images.githubusercontent.com/634562/99899018-ef653c00-2c5a-11eb-8ee7-f41cf449fb5b.png)

**Comment by glacambre** [comment] 2020-11-22 12:24
The "expected UI" depends on the theme you're using, so I'm not sure what it means here. Could you describe what is missing (colors, undercurl, something else?).

**Comment by benlieb** [comment] 2020-11-22 19:54
I get un undercurl in MacVim and a background color in terminal with all themes I've triedd. 

![image](https://user-images.githubusercontent.com/634562/99915433-7694cd00-2cb8-11eb-8f5c-3212eb049237.png)

![image](https://user-images.githubusercontent.com/634562/99915449-8ad8ca00-2cb8-11eb-8174-fd17f70709f9.png)

![image](https://user-images.githubusercontent.com/634562/99915476-c7a4c100-2cb8-11eb-933f-575b18cf4c47.png)

![image](https://user-images.githubusercontent.com/634562/99915500-edca6100-2cb8-11eb-8359-c6c0504a512b.png)

**Comment by alerque** [comment] 2020-11-22 20:54
Set spell is on, and missssspellings show.

![image](https://user-images.githubusercontent.com/173595/99916887-ed17e600-2d1d-11eb-8cbd-602453cdc7c5.png)

*How* they show is largely dependent on the colorscheme.

**Comment by benlieb** [comment] 2020-11-22 21:51
That's what I'd expect, but in this case set spell is on in all modes, and the colorscheme is the same. That said, I do have some firenvim specific settings that might be getting in the way. This is likely the case since it's working for you. These are my settings:

![image](https://user-images.githubusercontent.com/634562/99918139-c92ab500-2cc9-11eb-9d54-05fe0b378bb2.png)

**Comment by benlieb** [comment] 2020-11-22 22:09
I've whittled down my init.vim and ~/.vimrc files to the following, confirmed that `set spell?` is `spell` and the issue persists. 

The spell indicators are a missing in every `colorscheme` in firenvim. I absolutely love this extension, and I'd love to get to the bottom of this particular issue. 


![image](https://user-images.githubusercontent.com/634562/99918383-59b5c500-2ccb-11eb-8fb2-6eb34f7c8a13.png)

**Comment by glacambre** [comment] 2020-11-23 05:32
@benlieb I'm not seeing a `:set spelllang=en` in your init.vim - could you check if adding this setting changes anything?

**Comment by benlieb** [comment] 2020-11-23 05:47
That setting is in my ~/.vimrc Still no-go.

![image](https://user-images.githubusercontent.com/634562/99932073-c51f8700-2d0b-11eb-8125-aa577e705449.png)

Thanks for continuing to help with this, I really appreciate it. It would be AMAZING if this could work. This extension is already revolutionizing my web experience, and spellcheck would be the cherry on top. I'm pretty stumped by it.

**Comment by benlieb** [comment] 2020-11-23 07:53
I found that I can do this, but only when I directly enter it in firenvim:

![image](https://user-images.githubusercontent.com/634562/99938753-606d2800-2d1d-11eb-93cf-7e96ab700446.png)

It is strange that I would have to do this. It seems it might be related to [this issue](https://vi.stackexchange.com/questions/18295/how-to-set-a-colorscheme-that-still-shows-spelling-errors) or [this issue](https://stackoverflow.com/questions/6008921/how-do-i-change-the-highlight-style-in-vim-spellcheck)

What I also don't understand is that when I put `hi SpellBad guibg=#b9f5ff` in my vim.int file, it doesn't "take":

![image](https://user-images.githubusercontent.com/634562/99938995-ed17e600-2d1d-11eb-8166-affc543de873.png)

**Comment by glacambre** [comment] 2020-11-23 08:03
`guibg` is only for GUIs, if you want your highlighting to also work in terminals, you need to specify cterm colors too, e.g. `:hi SpellBad ctermfg=white ctermbg=red guifg=white guibg=red`. Since setting SpellBad manually works, I'm fairly certain that the issue comes from your colorschemes and not from Firenvim :)

Also when you make changes to your config, make sure to restart the Firenvim frame twice (or use the "reload settings" button in the Firenvim browser menu) - Firenvim preloads a neovim instance in order to make startup faster and so there's a "lag" between the version of your config on your disk and the one you're seeing when you create a Firenvim frame in your browser.

**Comment by benlieb** [comment] 2020-11-23 08:10
The only thing I'm having trouble with is the misspelling indicators in firenvim, which responds to `guibg` so that's all I'm putting in the block that checks for `g:started_by_firenvim`.

Even if there were an issue with the colorschemes (I verified this with no colorschemes in my configs at all), why would the last line (`hi SpellBad guibg=#b9f5ff`) in the following config not have any effect when put in the `init.vim`, but would only have an effect in when entered as a command in the firenvim instance text edit area?

```
let g:using_neovim='true'

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc

"--FireNVim Browser Ext----------------------------------------------
" keep at bottom to overwrite other config
if exists('g:started_by_firenvim')
  colorscheme reliable
  set nocursorline
  " these somehow let cmd(D)+v paste...
  tmap <D-v> <C-w>"+
  nnoremap <D-v> "+p
  vnoremap <D-v> "+p
  inoremap <D-v> <C-R><C-O>+
  cnoremap <D-v> <C-R><C-O>+
  set guifont=BitstreamVeraSansMono\ Nerd\ Font\ Mono:h10
  set laststatus=0 "removes status line
  let s:hidden_all = 1
  set noshowmode
  set noruler
  set laststatus=0
  set noshowcmd
  let g:firenvim_config = { 'localSettings': { '.*': { 'takeover': 'never' } } }
  set clipboard+=unnamed  "copies yanked stuff to system clipboard
  set spell
  hi SpellBad guibg=#b9f5ff
endif
```

**Comment by glacambre** [comment] 2020-11-23 08:14
If you think your config is overwriting your SpellBad setting, you can find out what line is doing this by running `:verbose hi SpellBad` :).

**Comment by benlieb** [comment] 2020-11-23 08:28
It seems that the colorscheme is writing to this last even though the setting itself occurs before my last setting of `hi SpellBad`.

![image](https://user-images.githubusercontent.com/634562/99940541-3453a600-2d21-11eb-9909-09f959b9e568.png)

For whatever reason the undercurl doesn't show up for me in firenvim (and I can see in your screenshot above that it is actually clipped on the bottom. Perhaps this is a lineheight issue. I found the `linespace` setting but it seems to have no effect to change it from 0 to more than that. 

I guess I either have to find out how to to manually set the `SpellBad` to something other than `undercurl` AFTER the colorscheme does, or write a function that I can execute easily to do it on demand. 

Thanks for all your help with this. I'm sure it's been annoying :p

**Comment by glacambre** [comment] 2020-11-23 08:52
You can make sure that this is a line height issue by spelling a word wrong in Firenvim, opening the dev tools and using the element inspector to select one of the letters of that word. The element should have a class named `.nvim_highlight_XX` where XX is a number and have a `text-decoration-line: underline` and a `text-decoration-style: wavy` rule.

I don't think Firenvim handles the `linespace` setting yet. I'll have to add that to the new renderer.

>Thanks for all your help with this. I'm sure it's been annoying :p

No problem :)

**Comment by benlieb** [comment] 2020-11-23 09:13
asdfasfd

Yeah, seems to be the case. Crazy that this is being rendered to HTML!

![image](https://user-images.githubusercontent.com/634562/99945227-19852f80-2d29-11eb-9923-8d6b94acad44.png)

**Comment by glacambre** [comment] 2020-11-23 09:53
>Crazy that this is being rendered to HTML!

I know :sob: . I've been working on a slightly saner renderer that uses a canvas instead. Hopefully I'll be able to merge before 2021 :smile: .

I'll close this issue since you've confirmed that the elements have the proper CSS rules but feel free to ask more questions should you need to :)

**Closed by glacambre** 2020-11-23 09:53 UTC

**Comment by benlieb** [comment] 2020-11-23 09:57
Thanks again for all your help. This extension is the best holiday present (early) I've ever gotten!

And for posterity, I did get this "working", but had to do it like this:

![image](https://user-images.githubusercontent.com/634562/99949075-4b00f980-2d2f-11eb-94c9-a198c3645f1f.png)
