### ISSUE TITLE
No filename

### ISSUE THREAD

**Issue by brandonkal** [glacambre/firenvim#434] opened 2020-02-20 03:30 UTC
It is now unusable as the file has no filename, so it is unable to :wq

- macOS: 10.13.6
- firenvim and nvim: latest
- firefox: latest

**Comment by glacambre** [comment] 2020-02-20 05:43
Could you try [this](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim)?

**Comment by marcopullo** [comment] 2020-02-23 01:46
Same issue with Chrome on macOS 10.15.3 with Chrome. Bisected git and found where filename stops getting set for me.

Latest commit filename correctly set on: https://github.com/glacambre/firenvim/commit/92187c88f71123854c7464cc0f5e1c19011383d8
Earliest commit filename stops being set on: https://github.com/glacambre/firenvim/commit/d9f3435509315b448398466c26fee63e0a1fd823

Why that commit would break anything I do not know.

**Comment by glacambre** [comment] 2020-02-23 06:02
@marcopullo thank you for taking the time to bisect this :). I assume you can still reproduce this issue [without your init.vim](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim)?

What happens when you press `<C-g>` in normal mode? What about `:w /tmp/x` and then `:q`? What does `:ls` print? What about `:autocmd BufWrite`?

**Comment by marcopullo** [comment] 2020-03-08 19:48
I had trouble initially trying to get the plugin working without an init.vim, which is why I ended up bisecting, but haven't had time to follow up further until now. Trying latest releases though the file name is getting set correctly so no issues. Typing this comment successfully from firenvim on Chrome+macOS.

**Comment by glacambre** [comment] 2020-03-09 04:42
Thanks for letting me know! Since @brandonkal hasn't replied, I'll assume that his problem is fixed too and close this issue :)

**Closed** 2020-03-09 04:43 UTC
Labels: blocked:awaiting-author
