### ISSUE TITLE
Font size changes between displays

### ISSUE THREAD

**Issue by ankitp4t3l** [glacambre/firenvim#869] opened 2021-01-11 20:20 UTC
**Edit from glacambre**: This issue is not about small fonts. If you have issues with fonts being too smal, use `guifont`, see `:help guifont` for more information.

-----------------------------------

First of all, thanks for such a great plugin.

- OS Version: mac x86-64
- Browser Version:  Firefox 83.0
- Browser Addon Version: 0.2.2
- Neovim Plugin Version: 0.2.2
- What I tried to do: Edit text
- What happened: The text size (font size) is too small when I open firenvim on my Mac's built in display, and it's just about right when I open firenvim on my external display. Moving the browser window between displays also changes the text size. The following video demonstrates the issue (with narration).

https://user-images.githubusercontent.com/10745379/104232746-024fed80-540e-11eb-9a35-7e7ff018d5f6.mp4

**Comment by glacambre** [comment] 2021-01-12 05:45
Hi, thanks for the report. I see that you have Firefox zoomed-in, could you zoom back to 100%, open the javascript console (`<CS-I>`) and take the following measurements on both screens:
- window.devicePixelRatio
- window.innerHeight
- window.innerWidth
- window.outerHeight
- window.outerWidth
- window.pageXOffset
- window.pageYOffset

I think what's happening here is that Firenvim is adjusting for the DPI of the external screen twice (once by multiplying everything by devicePixelRatio and once by expressing sizes in points which Firefox decides to adjust on its own).

**Comment by ankitp4t3l** [comment] 2021-01-12 21:21
On the mac
```
window.devicePixelRatio = 2
window.innerHeight      = 420
window.innerWidth       = 1507
window.outerHeight      = 986
window.outerWidth       = 1507
window.pageXOffset      = 0
window.pageYOffset      = 1724
```

On the external display
```
window.devicePixelRatio = 1
window.innerHeight      = 420
window.innerWidth       = 1507
window.outerHeight      = 986
window.outerWidth       = 1507
window.pageXOffset      = 0
window.pageYOffset      = 1612
```

**Comment by glacambre** [comment] 2021-01-13 07:14
@ankip4t3l : Could you load [this version](https://github.com/glacambre/firenvim/files/5806963/firenvim-0.2.3.zip) in a fresh firefox profile (you can create and launch new firefox profiles by navigating to `about:profiles` in Firefox) and tell me if it changes anything?

**Comment by ankitp4t3l** [comment] 2021-01-16 20:15
Nope - I installed the version you linked (through dev mode on a new profile), and then updated my neovim plugin to 0.2.3 (to match the browser plugin version), and the text on the mac is still smaller than the external display.

**Comment by glacambre** [comment] 2021-01-17 14:04
Thank you for trying it out. I don't know how to solve this issue - we need to multiply everything by devicePixelRatio in order to take browser zoom into account (otherwise we get blurry fonts) but it looks like your OS or browser is applying its own scaling somewhere in the pipeline that makes things bigger than they need to be :/.

**Comment by isamert** [comment] 2021-01-18 12:40
Just wanted to add that this also happens in Chromium based browsers on macOs. So it's probably related to retina display (or whatever that is, I don't really understand how these macs work).

**Comment by ymukhin** [comment] 2021-02-02 19:26
Hi all, just want to add that in the absence of a proper fix to default font scaling on macOS, I was able to make use of firenvim by manually adjusting the font in the browser textarea running neovim with `:set guifont=Menlo:h16`.

**Comment by devyhia** [comment] 2021-02-03 11:34
I am having the same problem with an external 4K display that is being scaled to 2X (i.e. like the retina display behavior on the Macbook).

This could be solved by adjusting the guifont (as previously indicated) if we could figure which monitor the neovim is embedded in. Or, better yet, if we could figure the pixel density on the display that hosts the neovim instance.

**Comment by glacambre** [comment] 2021-02-03 12:22
>if we could figure the pixel density on the display that hosts the neovim instance.

We can, this is the value [window.devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) represents :). In fact, Firenvim already takes it into account[¹](https://github.com/glacambre/firenvim/blob/696b978c76605be6acb22be4a7da2fa72b679473/src/render/RedrawCanvas.ts#L32)[²](https://github.com/glacambre/firenvim/blob/696b978c76605be6acb22be4a7da2fa72b679473/src/render/RedrawCanvas.ts#L306)[³](https://github.com/glacambre/firenvim/blob/696b978c76605be6acb22be4a7da2fa72b679473/src/render/RedrawCanvas.ts#L863). If it didn't we'd get blurry fonts when the browser is zoomed-in.

**Comment by glacambre** [comment] 2021-02-04 06:08
Attempted something else. @ankip4t3l could you let me know if Firenvim's size still changes between your two screens with [this version](https://github.com/glacambre/firenvim/files/5923560/chrome.zip)?

**Comment by wisonye** [comment] 2021-02-10 23:27
Hi, below is the `firenvim` settings in my `init.vim`. It fixed the problem:

```vim
" ----------------------------------------------------------------------------
" 'glacambre/firenvim'
" ----------------------------------------------------------------------------
let g:firenvim_config = { 
    \ 'globalSettings': {
        \ 'alt': 'all',
    \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'cmdline': 'neovim',
            \ 'content': 'text',
            \ 'priority': 0,
            \ 'selector': 'textarea',
            \ 'takeover': 'always',
        \ },
    \ }
\ }

" Disable `firenvim` for the particular webiste
let fc = g:firenvim_config['localSettings']
" let fc['https?://[^/]+\.co\.uk/'] = { 'takeover': 'never', 'priority': 1 }
let fc['https?://twitter.com/'] = { 'takeover': 'never', 'priority': 1 }
let fc['https?://twitter.tv/'] = { 'takeover': 'never', 'priority': 1 }


" Change `firenvim` file type to enable syntax highlight, `coc` works perfectly
" after this settings!!!
autocmd BufEnter github.com_*.txt set filetype=markdown
autocmd BufEnter txti.es_*.txt set filetype=typescript


" Increase the font size to solve the `text too small` issue
function! s:IsFirenvimActive(event) abort
    if !exists('*nvim_get_chan_info')
        return 0
    endif
    let l:ui = nvim_get_chan_info(a:event.chan)
    return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction

function! OnUIEnter(event) abort
    if s:IsFirenvimActive(a:event)
        " Disable the status bar
        set laststatus=0

        " Increase the font size
        set guifont=SauceCodePro\ Nerd\ Font:h18
    endif
endfunction

autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

</br>

Of course, you need to make sure to change the font name to one you're using in your environment!
Also, make sure to use `h:{SIZE}` rather than the ` {SIZE}`:

- This will work in `firenvim`:

    ```vim
    set guifont=SauceCodePro\ Nerd\ Font:h18

- This won't work in `firenvim`:

    ```vim
    set guifont=SauceCodePro\ Nerd\ Font\ 18
    ```

</br>

Here is the screenshot when I'm writing new issue here:

![solved-font-too-small-issue](https://user-images.githubusercontent.com/3477321/107585645-8393dd80-6c63-11eb-82ba-860776737fc7.png)


As you can see that it prints out the new specified font setting when I run `:set guifont?` inside the `firenvim`.

Hope that can help you:)

**Comment by wisonye** [comment] 2021-02-11 07:20
> @wisonye thanks :)!
> 
> Can you confirm that you had the same problem as @ankitp4t3l, which was different font sizes on different screens?

@glacambre Sorry about that, I can't confirm for the external monitor case, as I don't have an external monitor:)

My comment just wants to focus on part of his issue which is:

**`The text size (font size) is too small when I open firenvim on my Mac's built-in display`**

I use `MacBookPro` 15 inches and I got the same issue whit that, then I solved it and want to share back, that's it :)

**Comment by jdhao** [comment] 2021-02-15 09:06
I have the same issue as @wisonye . I have no external display. The default font size used by firenvim is too small. I can confirm that setting the `guifont` option fixes the issue. My setting related to firenvim:

```
if exists('g:started_by_firenvim') && g:started_by_firenvim
  set guifont=Iosevka\ Nerd\ Font:h18
  " general options
  set laststatus=0 nonumber noruler noshowcmd

  " general config for firenvim
  let g:firenvim_config = {
      \ 'globalSettings': {
          \ 'alt': 'all',
      \  },
      \ 'localSettings': {
          \ '.*': {
              \ 'cmdline': 'neovim',
              \ 'priority': 0,
              \ 'selector': 'textarea',
              \ 'takeover': 'never',
          \ },
      \ }
  \ }

  augroup firenvim
    autocmd!
    autocmd BufEnter *.txt setlocal filetype=markdown
  augroup END
endif

```

**Comment by ankitp4t3l** [comment] 2021-02-21 22:46
> Attempted something else. @ankitp4t3l @devyhia could you let me know if Firenvim's size still changes between your two screens with [this version](https://github.com/glacambre/firenvim/files/5923560/chrome.zip)? This version tries to convert the pixel sizes the browser gives Firenvim into point sizes.

No luck with this one either

**Comment by harshas-repo** [comment] 2021-03-03 13:26
Hey guys font size is very small on MacOs Mohave, Browser : Firefox, What's the fix ??. Looks like @

> Hi, below is the `firenvim` settings in my `init.vim`. It fixed the problem:
> 
> ```viml
> " ----------------------------------------------------------------------------
> " 'glacambre/firenvim'
> " ----------------------------------------------------------------------------
> let g:firenvim_config = { 
>     \ 'globalSettings': {
>         \ 'alt': 'all',
>     \  },
>     \ 'localSettings': {
>         \ '.*': {
>             \ 'cmdline': 'neovim',
>             \ 'content': 'text',
>             \ 'priority': 0,
>             \ 'selector': 'textarea',
>             \ 'takeover': 'always',
>         \ },
>     \ }
> \ }
> 
> " Disable `firenvim` for the particular webiste
> let fc = g:firenvim_config['localSettings']
> " let fc['https?://[^/]+\.co\.uk/'] = { 'takeover': 'never', 'priority': 1 }
> let fc['https?://twitter.com/'] = { 'takeover': 'never', 'priority': 1 }
> let fc['https?://twitter.tv/'] = { 'takeover': 'never', 'priority': 1 }
> 
> 
> " Change `firenvim` file type to enable syntax highlight, `coc` works perfectly
> " after this settings!!!
> autocmd BufEnter github.com_*.txt set filetype=markdown
> autocmd BufEnter txti.es_*.txt set filetype=typescript
> 
> 
> " Increase the font size to solve the `text too small` issue
> function! s:IsFirenvimActive(event) abort
>     if !exists('*nvim_get_chan_info')
>         return 0
>     endif
>     let l:ui = nvim_get_chan_info(a:event.chan)
>     return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
>       \ l:ui.client.name =~? 'Firenvim'
> endfunction
> 
> function! OnUIEnter(event) abort
>     if s:IsFirenvimActive(a:event)
>         " Disable the status bar
>         set laststatus=0
> 
>         " Increase the font size
>         set guifont=SauceCodePro\ Nerd\ Font:h18
>     endif
> endfunction
> 
> autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
> ```
> 
> 
> Of course, you need to make sure to change the font name to one you're using in your environment!
> Also, make sure to use `h:{SIZE}` rather than the ` {SIZE}`:
> 
> * This will work in `firenvim`:
>   ```viml
>   set guifont=SauceCodePro\ Nerd\ Font:h18
>   ```
> * This won't work in `firenvim`:
>   ```viml
>   set guifont=SauceCodePro\ Nerd\ Font\ 18
>   ```
> 
> 
> Here is the screenshot when I'm writing new issue here:
> 
> ![solved-font-too-small-issue](https://user-images.githubusercontent.com/3477321/107585645-8393dd80-6c63-11eb-82ba-860776737fc7.png)
> 
> As you can see that it prints out the new specified font setting when I run `:set guifont?` inside the `firenvim`.
> 
> Hope that can help you:)

Pin this message or include it in troubleshooting or in documentation, it helped me resolve the small font issue on MacOS Mohave, Browser: Firefox. @wisonye Thanks man. Saved a lot of time for me.

**Comment by glacambre** [comment] 2021-03-03 13:30
I've opened https://github.com/glacambre/firenvim/issues/972 for font size issues. Please stop spamming this issue which is about a different problem.

**Comment by ankitp4t3l** [comment] 2021-04-27 04:16
@glacambre I was reading the MDN docs and [this section](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#examples) led me to suspect that perhaps while the firenvim code is scaling the canvas dimensions by the devicePixelRatio, it is *not* scaling the shapes drawn by the same ratio. Hence when the canvas is scaled to fit the CSS size, the shapes end up too small.

I'll provide an update once I get a chance to test the code changes.

**Comment by Gelio** [comment] 2022-07-14 17:51
To anyone interested: I pushed https://github.com/glacambre/firenvim/pull/1385 which was merged and I believe is on its way to the browser addon stores. It has a chance to fix your DPI scaling issues. It did for me. See the PR for a comparison

**Comment by glacambre** [comment] 2022-07-17 07:32
Closing this issue due to the merge of #1385. If you're still experiencing this problem, let me know and I'll re-open.

**Closed by glacambre** 2022-07-17 07:32 UTC
Labels: help wanted
