### ISSUE TITLE
Slow trigger with new rendering

### ISSUE THREAD

**Issue by enovid** [glacambre/firenvim#890] opened 2021-01-22 06:15 UTC
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 88.0.4324.96
- Browser Addon Version: 0.2.3
- Neovim Plugin Version: 0.2.3
- What I tried to do: Trigger Firenvim in a Jupyter Notebook cell
- What happened: Firenvim replaces the cell with a blank buffer and **takes anywhere from 10 to 30+ seconds to become active** and show the text. Meanwhile, the browser hangs and crashes if you try to navigate to a different tab or window. 

----

- Some context: I've used Firenvim for years as part of my workflow with Jupyter Notebooks and never had this issue. 
- My temporary solution: I reverted to the old html rendering which seems to solve the issue.
```
    \ 'localSettings': {
        \ '.*': {
            \ 'renderer': 'html',
        \ },
    \ }
```

See the videos for a comparison between html rendering and the new rendering method. The new rendering hangs for 30 seconds before the buffer becomes active.

**HTML Rendering:**

[![HTML Rendering]()](https://user-images.githubusercontent.com/8015376/105453415-f39adf00-5c34-11eb-999f-a90c75ab78f1.mp4)

**New Rendering:**

[![New rendering]()](https://user-images.githubusercontent.com/8015376/105453429-fac1ed00-5c34-11eb-87d9-381603e963ec.mp4)

**Comment by glacambre** [comment] 2021-01-22 06:39
Wow, weird bug, thanks a lot for reporting it!

Could you record a performance profile of the new renderer? To do this, use `<CS-I>` to open the dev tools, navigate to the performance tab, click on the record button (full circle on the left side of the dev tools), start Firenvim, wait for everything to be drawn, press `:q!`, wait for the frame to disappear, click "Stop" and then save the performance profile (arrow pointing down near the record button).

After that, please upload it here, hopefully this will help me figure out what's wrong :).

**Comment by enovid** [comment] 2021-01-23 00:28
> Could you record a performance profile of the new renderer? 
> 
> After that, please upload it here, hopefully this will help me figure out what's wrong :).

@glacambre [performance-profile.zip](https://github.com/glacambre/firenvim/files/5859256/performance-profile.zip)

Please let me know if you need additional information. And thank you for maintaining this fantastic tool!

**Comment by glacambre** [comment] 2021-01-23 06:16
@enovid Thanks, the perf profile was all I needed :). According to the profile you uploaded, Firenvim is stuck on a single call to [getImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData). This means that this is issue is a Chrome bug (possibly [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=1001845)?).

I've tried a workaround, could you download [this file](https://github.com/glacambre/firenvim/files/5859766/chrome.zip), unzip it, go to `chrome://extensions`, remove firenvim, enable developper mode (toggle button on the top right corner), click "load unpacked" (top left corner), select the directory that contains the files you unzipped and then try the new renderer again?

If this new version doesn't improve Firenvim's performance, could you remove the unpacked extension, download Firenvim from the chrome store again, go to `chrome://settings/?search=hardware`, disable hardware acceleration, and let me know if that improves the new renderer's performance? (You'll probably want to re-enable hardware acceleration after this experiment.)

**Comment by enovid** [comment] 2021-01-27 19:22
> I've tried a workaround, could you download this file, unzip it, go to chrome://extensions, remove firenvim, enable developper mode (toggle button on the top right corner), click "load unpacked" (top left corner), select the directory that contains the files you unzipped and then try the new renderer again?

@glacambre the unpacked extension made no difference. One thing I noticed with both the chrome extension and unpacked version is the first time I activate a cell on a page, there's no delay, but after the first activation, it starts to have a 30 second delay. 

> If this new version doesn't improve Firenvim's performance, could you remove the unpacked extension, download Firenvim from the chrome store again, go to chrome://settings/?search=hardware, disable hardware acceleration, and let me know if that improves the new renderer's performance?

Disabling hardware acceleration fixes the issue.

---

Please let me know if there's anything else I can do to help! Sorry about the delay, the past few days have been busy.

**Comment by glacambre** [comment] 2021-01-28 04:56
Thank you for this information. Unfortunately I think there's nothing I can do here, so I've opened https://bugs.chromium.org/p/chromium/issues/detail?id=1171586 . I'm not very confident this bug will ever be fixed unless we attempt to tackle it ourselves and as I can't reproduce it I can't fix it.

I don't know what to do here. I was planning on completely removing the old renderer from Firenvim. They have already grown appart a lot (I fixed many bugs in the new one that were and still are present in the old one) :/.

**Comment by glacambre** [comment] 2021-05-09 12:37
FYI I am going to drop support for the old renderer in next release (it's doubling the amount of work I have to do to upgrade typescript in https://github.com/glacambre/firenvim/pull/1025 ). I've uploaded a built version of the browser plugin to github in case it is needed later: https://github.com/glacambre/firenvim/releases/tag/v0.2.6 .

**Comment by glacambre** [comment] 2022-02-19 05:18
@enovid People reported that the problem you're describing here has disappeared for them in #1068, so I'll close this issue. If you're still experiencing problems, let me know and I'll re-open :)

**Closed by glacambre** 2022-02-19 05:18 UTC
Labels: host:chrome, os:linux, blocked, cant-reproduce
